# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Junteng Liu | Homepage"
title_separator          : "-"
name                     : &name "Junteng Liu"
description              : &description "PhD candidate in Computer Science at HKUST NLP Group"
url                      : https://tahasman-bot.github.io
baseurl                  : ""
repository               : "tahasman-bot/LJT-Homepage"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Junteng Liu"
  bio              : "I am a first-year PhD candidate at the [HKUST NLP Group](https://hkust-nlp.hkust.edu.hk/) advised by [Professor Junxian He](https://junxianhe.com/). I graduated from [Shanghai Jiao Tong University](https://www.sjtu.edu.cn/) in June 2024. My research focuses on natural language processing and machine learning."
  location         : "Hong Kong"
  employer         : "Hong Kong University of Science and Technology"
  email            : "jliugi@connect.ust.hk"
  googlescholar    : "https://scholar.google.com/citations?user=tbK9jl4AAAAJ&hl=en"
  github           : "Vicent0205"
  twitter          : "junteng88716710"

# Publication Category
publication_category:
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   : 

# SEO Related
google_site_verification :
bing_site_verification   :

# Social Sharing
twitter:
  username               : &twitter "junteng88716710"

# Analytics
analytics:
  provider               :  "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  - _talks
  - _teaching
  - _portfolio
  - _posts
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development